### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mohammedkhudair57**
little changes commit 
form the forked one

### CODE REVIEW

**Comment by mohammedkhudair57** [comment]
Please check my code

**Review by mohammedkhudair57 — COMMENTED** [review]
Hi!!

**Comment by MohammedKhudair** [comment]
this repo has a conflict

**Review by MohammedKhudair — CHANGES_REQUESTED** [review]
Please change the code to mach the ruls

**Comment by MohammedKhudair** [comment]
Well done, Mohammed 👌

**Pull request merged**
